on: push
name: npm build, lint, test and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: actions/npm@master
        with:
          args: install
      - name: docker login
        run: docker login --username "${{ secrets.Docker_username }}" --password "${{ secrets.Docker_password }}"
      - name: Docker build
        run: docker build . --file Dockerfile --tag ugoslim/nodebackend
      - name: docker push
        run: docker push ugoslim/nodebackend
 
