on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
name: npm build, push docker
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        uses: actions/npm@v2
        with:
          args: install
      - name: docker login
        run: docker login --username "${{ secrets.Docker_username }}" --password "${{ secrets.Docker_password }}"
      - name: Docker build
        run: docker build . --file Dockerfile --tag ugoslim/nodebackend
      - name: docker push
        run: docker push ugoslim/nodebackend
 
